name: Pac-Man Contribution Graph

on:
  schedule:
    # Runs at 12 AM UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pac-Man contribution graph
        uses: Rudracodes/pacman-github-contribution@main
        with:
          github_user_name: ${{ github.repository_owner }}
          output_branch: 'output'
